displayName=Face Swap
author=vahnx
description=Swap faces onto OSRS player or NPC models.
tags=face,swap,appearance,cosmetic,osrs,gnomonkey,odablock,sardaco,asianandy,mintmadcow,fox,grim,kingcondor,alfie,dearlola,beggar,tpapaslice,zecookies,prisonjoe,eliop14,jillyfish,skillspecs,tastylife,brettdog,mmorpg,rsfelon,mrnosleep,sicknerd
version=0.10.0
plugins=com.faceswap.FaceSwapPlugin
build=standard
